[theme]
base = "light"
primaryColor = "#18865F"
backgroundColor = "#F5F8F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#173C65"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
